class EventTypes:
    SPELL_AURA_APPLIED = 'SPELL_AURA_APPLIED'
    SPELL_AURA_REMOVED = 'SPELL_AURA_REMOVED'
    SPELL_AURA_APPLIED_DOSE = 'SPELL_AURA_APPLIED_DOSE'
    SPELL_DAMAGE = 'SPELL_DAMAGE'
    SWING_MISSED = 'SWING_MISSED'
    SWING_DAMAGE = 'SWING_DAMAGE'

DAY_IN_MILLIS = 1000*60*60*24

